spring:
  application:
    name: planefinder

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sifehe90

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
