spring:
  application:
    name: coffee-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sifehe90
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create | create-drop | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
